### ISSUE TITLE
Report error 'prot'

### ISSUE THREAD

**Issue by Audra-Leigh** [cjneely10/EukMetaSanity#18]
Good afternoon,

I'm trying to run your pipeline by utilizing commands for EukMS_run and EukMS_report. I keep getting an error message pertaining to busco. In the .yaml file, I have all the information for the system and the libraries. Maybe I'm entering the wrong information in the yaml file for report processing. 

For busco I have the following information:
Quality:
  # Number of threads task will use
  threads: 10
  # Amount of memory task will use (in GB)
  memory: 16
  time: 4:00:00
  skip: false
  dependencies:
    Busco:
      program: busco
      mode: prot
      lineage: eukaryota
      FLAGS:
        -f

Here is the code for the job submission:

yapim run -i /fs/ess/PAS1802/Audra/MicEuk_gDNA_optimization/sequencing_run3/eukmeta/21FACS/results/run/21FACS-1000/ -c /fs/ess/PAS1802/Audra/MicEuk_gDNA_optimization/sequencing_run3/eukmeta/jobs/21FACS-report-config.yaml -p /users/PAS1212/osu10462/EukMetaSanity/bin/report-pipeline/ -o /fs/ess/PAS1802/Audra/MicEuk_gDNA_optimization/sequencing_run3/eukmeta/21FACS/report/

I've tried variations of prot and protein (I tried this due to busco github page). I get the following error message: 

Traceback (most recent call last):
  File "/users/PAS1212/osu10462/miniconda3/envs/EukMS_report/lib/python3.8/site-packages/yapim/tasks/task.py", line 303, in try_run
    self.run()
  File "/users/PAS1212/osu10462/EukMetaSanity/bin/report-pipeline/dependencies/busco/busco.py", line 30, in run
    "-i", self.input["prot"],
KeyError: 'prot'

How do I fix this? Am I missing some key piece of information?

Thanks

Audra-Leigh

**Comment by cjneely10** [comment]
Hi @Audra-Leigh,

Thank you for your issue post.

Apologies for the confusion. For the `run` pipeline, if you used:
```
yapim run -i /path/to/genome_dir -p $EukMS_run -o out -c run-pipeline.yaml
```
then, for the `report` pipeline, you would use:
```
yapim run -p $EukMS_report -o out -c report-pipeline.yaml
```

Notice that, in the second command, the `-i` flag is not provided - the `report` pipeline will only annotate the input data that was processed by the `run` pipeline. Also, the output directories are the same in both cases - the data is shared between the pipeline runs.

Hopefully this helps, please let me know if there are any further issues.

Chris
