### ISSUE TITLE
Issue with database installation

### ISSUE THREAD

**Issue by michoug** [cjneely10/EukMetaSanity#5]
Hi, 
I got this error when running : `download-data -t 28 -d /work/sber/Databases/EukMetaSanity/`

```
/home/gmichoud/miniconda3/envs/EukMS_run/bin/mmseqs createtaxdb /work/sber/Databases/EukMetaSanity/odb-mmetsp_db /work/sber/Databases/EukMetaSanity/tmp --ncbi-tax-dump /work/sber/Databases/EukMetaSanity/
/home/gmichoud/miniconda3/envs/EukMS_run/bin/mmseqs createlinindex /work/sber/Databases/EukMetaSanity/MMETSP /work/sber/Databases/EukMetaSanity/tmp --threads 28 --remove-tmp-files
/home/gmichoud/miniconda3/envs/EukMS_run/bin/mmseqs createlinindex /work/sber/Databases/EukMetaSanity/odb-mmetsp_db /work/sber/Databases/EukMetaSanity/tmp --threads 28 --remove-tmp-files
/home/gmichoud/miniconda3/envs/EukMS_run/bin/mmseqs createlinindex /work/sber/Databases/EukMetaSanity/ortho_db /work/sber/Databases/EukMetaSanity/tmp --threads 28 --remove-tmp-files
Traceback (most recent call last):
  File "/home/gmichoud/miniconda3/envs/EukMS_run/bin/download-data", line 62, in <module>
    DataDownloader.run()
  File "/home/gmichoud/miniconda3/envs/EukMS_run/lib/python3.8/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/home/gmichoud/miniconda3/envs/EukMS_run/bin/download-data", line 58, in main
    update_config_files(self._working_dir, self._bin_dir)
  File "/home/gmichoud/miniconda3/envs/EukMS_run/lib/python3.8/site-packages/EukMetaSanity/data/config_generation_utils.py", line 13, in update_config_files
    for config_file in glob.glob(os.path.join(os.path.dirname(eukms_bin_dir), "*", "*", "*-config.*")):
  File "/home/gmichoud/miniconda3/envs/EukMS_run/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any ideas?

**Comment by cjneely10** [comment]
Hello,

Thank you for checking out the software!

I think the download script was unable to find the `EukMS_run` environment variable we set in the installation process.

Did you reset your bash environment after running the `INSTALL.sh` script? If you run `echo $EukMS_run`, you should get back a valid path

**Comment by michoug** [comment]
Hi,
Thanks, indeed I missed this part
Best
Greg
