### ISSUE TITLE
download-data script error

### ISSUE THREAD

**Issue by JSSaini** [cjneely10/EukMetaSanity#9]
download-data -t 1 -d ./

```Downloading data
/home/users/s/saini7/anaconda3/envs/EukMS_refine/bin/mmseqs createdb /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/odb10v1_all_og_fasta.tab /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/ortho_db
Traceback (most recent call last):
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/bin/download-data", line 73, in <module>
    DataDownloader.run()
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/bin/download-data", line 54, in main
    db_download()
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/EukMetaSanity/data/data_types.py", line 26, in __call__
    self.run(local["mmseqs"]["createdb", self.data, self.db_name])
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/EukMetaSanity/data/data.py", line 26, in run
    return cmd()
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/commands/base.py", line 95, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/commands/base.py", line 225, in run
    return p.run()
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/commands/base.py", line 187, in runner
    return run_proc(p, retcode, timeout)
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/commands/processes.py", line 206, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/users/s/saini7/anaconda3/envs/EukMS_refine/lib/python3.8/site-packages/plumbum/machines/base.py", line 21, in verify
    raise ProcessExecutionError(getattr(self, "argv", None), self.returncode,
plumbum.commands.processes.ProcessExecutionError: Command line: ['/home/users/s/saini7/anaconda3/envs/EukMS_refine/bin/mmseqs', 'createdb', '/srv/beegfs/scratch/users/s/saini7/EukMetaSanity/odb10v1_all_og_fasta.tab', '/srv/beegfs/scratch/users/s/saini7/EukMetaSanity/ortho_db']
Exit code: 1
Stdout:  | /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/ortho_db exists and will be overwritten.
         | createdb /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/odb10v1_all_og_fasta.tab /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/ortho_db
         |
         | MMseqs Version:              12.113e3
         | Database type                0
         | Shuffle input database       true
         | Createdb mode                0
         | Write lookup file            1
         | Offset of numeric ids        0
         | Compressed                   0
         | Verbosity                    3
         |
         | Converting sequences
         | [=================================================================================================== 1 Mio. sequences processed
         | ===================================================================================================  2 Mio. sequences processed
         | ===================================================================================================  3 Mio. sequences processed
         | ===================================================================================================  4 Mio. sequences processed
         | ===================================================================================================  5 Mio. sequences processed
         | ===================================================================================================  6 Mio. sequences processed
         | ===================================================================================================  7 Mio. sequences processed
         | ===================================================================================================  8 Mio. sequences processed
         | ===================================================================================================  9 Mio. sequences processed
         | ===================================================================================================  10 Mio. sequences processed
         | ===================================================================================================  11 Mio. sequences processed
         | ===================================================================================================  12 Mio. sequences processed
         | ===================================================================================================  13 Mio. sequences processed
         | ===================================================================================================  14 Mio. sequences processed
         | ===================================================================================================  15 Mio. sequences processed
         | ===================================================================================================  16 Mio. sequences processed
         | ===================================================================================================  17 Mio. sequences processed
         | ===================================================================================================  18 Mio. sequences processed
         | ===================================================================================================  19 Mio. sequences processed
         | ===================================================================================================  20 Mio. sequences processed
         | ===================================================================================================  21 Mio. sequences processed
         | ===================================================================================================  22 Mio. sequences processed
         | ===================================================================================================  23 Mio. sequences processed
         | ===================================================================================================  24 Mio. sequences processed
         | ===================================================================================================  25 Mio. sequences processed
         | ===================================================================================================  26 Mio. sequences processed
         | ===================================================================================================  27 Mio. sequences processed
         | ===================================================================================================  28 Mio. sequences processed
         | ===================================================================================================  29 Mio. sequences processed
         | ===================================================================================================  30 Mio. sequences processed
         | ===================================================================================================  31 Mio. sequences processed
         | ===================================================================================================  32 Mio. sequences processed
         | ===================================================================================================  33 Mio. sequences processed
         | ===================================================================================================  34 Mio. sequences processed
         | ===================================================================================================  35 Mio. sequences processed
         | ===================================================================================================  36 Mio. sequences processed
         | ===================================================================================================  37 Mio. sequences processed
         | ==============================================
Stderr:  | Can not open index file /srv/beegfs/scratch/users/s/saini7/EukMetaSanity/ortho_db_h.index.11!```

**Comment by JSSaini** [comment]
Please let me know how to troubleshoot this error. Thank you.

**Comment by cjneely10** [comment]
Hi @JSSaini 

Sorry about ignore the closed issue, hit the wrong button.

Please re-try your download without the -d flag. There was a small bug for which I pushed a fix, but your version of the script should work if the flag is not used.

Sorry for the inconvenience, thank you for your patience,

Chris
